name: Push to GitHub registry

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        working-directory: ./.devcontainer
        run: |
          docker build . --tag ghcr.io/easy-ebpf/tutorial-simple-example:latest
          docker push ghcr.io/easy-ebpf/tutorial-simple-example:latest
